### ISSUE TITLE
_init_errcodes fails with ShortRead

### ISSUE THREAD

**Issue by motoz** [miccoli/pyownet#2]
Hello, I was trying out pyownet instead of the old ownet module and got this error:
````python
from pyownet import protocol
proxy = protocol.proxy('192.168.1.8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyownet/protocol.py", line 653, in proxy
    owp._init_errcodes()
  File "pyownet/protocol.py", line 408, in _init_errcodes
    m for m in bytes2str(self.read(PTH_ERRCODES)).split(','))
  File "pyownet/protocol.py", line 471, in read
    ret, data = self.sendmess(MSG_READ, str2bytez(path), size=size)
  File "pyownet/protocol.py", line 422, in sendmess
    ret, _, data = conn.req(msgtype, payload, flags, size, offset)
  File "pyownet/protocol.py", line 334, in req
    fromhead, data = self._read_msg()
  File "pyownet/protocol.py", line 372, in _read_msg
    "instead of {1:d}".format(len(payload), header.payload))
pyownet.protocol.ShortRead: short payload, got 1424 bytes instead of 4983
````
Owserver version is: 2.8p15-1 from debian stable (actually raspbian)

This "fixes" it, but obviously there is something else going on:

````python
@@ -403,10 +405,11 @@ class _Proxy(object):
     def _init_errcodes(self):
 
         # fetch errcodes array from owserver
+        print ('get errcodes')
         try:
             self.errmess = _errtuple(
                 m for m in bytes2str(self.read(PTH_ERRCODES)).split(','))
-        except OwnetError:
+        except (OwnetError, ShortRead):
             # failed, leave the default empty errcodes
             pass
````
I added a print (payload) to _read_msg and got this:

proxy = protocol.proxy('192.168.1.8', verbose=True)
('192.168.1.4', 50429) -> ('192.168.1.8', 4304)
-> _ToServerHeader(version=0, payload=0, type=1, flags=0, size=0, offset=0)
.. ''
<- _FromServerHeader(version=0, payload=0, ret=0, flags=0, size=0, offset=0)
('192.168.1.4', 50429) xx ('192.168.1.8', 4304)
('192.168.1.4', 50430) -> ('192.168.1.8', 4304)
-> _ToServerHeader(version=0, payload=32, type=2, flags=0, size=65536, offset=0)
.. '/settings/return_codes/text.ALL\x00'
<- _FromServerHeader(version=0, payload=4983, ret=4983, flags=0, size=4983, offset=0)
Good result,Startup - command line parameters invalid,legacy - No such entity,Startup - a device could not be opened,legacy - Interrupted,legacy - IO error,Startup - network could not be opened,Startup - Avahi library could not be loaded,Startup - Bonjour library could not be loaded,legacy - Bad filesystem,Startup - zeroconf communication problem,legacy - Temporary interruption,legacy - memory exhausted,legacy - Access error,legacy - Communication fault,Startup - memory could not be allocated,legacy - Busy,Program - not initialized,Program - not yet ready,legacy - No such device,legacy - Not a directory,legacy - Is a directory,legacy - Invalid transaction,Program - closing,Program - closed,Program - cannot close,Path - input path too long,Path - bad path syntax,Device - Device name bad CRC8,Device - Unrecognized device name or alias,legacy - Read-only file system,Device - alias name too long,Device - unrecognized device property,Device - device property not an array,legacy - Out of range,Device - device property should be an array,legacy - Name too long,Device - device not a bit field,Device - array index out of range,Device - device property not a subpath,legacy - Loop discovered,Device - device not found,legacy - No message,Device - other device error,Bus - bus short,Bus - no such bus,Bus - bus not appropriate,Bus - bus not responding,Bus - bus being reset,Bus - bus closed,Bus - bus could not be ope

Seems like the response is cut short for some reason.

**Comment by miccoli** [comment]
I suspect that this problem is linked to `self.socket.recv(header.payload, _MSG_WAITALL)` not working as expected on [this line](https://github.com/miccoli/pyownet/blob/master/pyownet/protocol.py#L368). (BTW trusting _MSG_WAITALL is indeed a known source of troubles, I should have known better.) You can try the experimental version in commit 93f8137ac95460830c50ed39d3c421286b6d165b which should fix the problem: just checkout feature branch [socket](https://github.com/miccoli/pyownet/tree/socket) to test this different implementation.

Thank you very much for your report: if the experimental code fixes your problem I will merge it in the master branch.

**Comment by motoz** [comment]
The socket branch works fine, thank you!
Ownet is causing me trouble so I'll try to replace it with pyownet. Your project seems to be in much better shape!

**Comment by motoz** [comment]
I tried to find some information on _MSG_WAITALL, but I can only find mentions of it being unreliable or absent on windows. I was trying pyownet on ubuntu 14.04, so apparently it's not only windows that causes trouble.

**Comment by miccoli** [comment]
Commit 0990acf6d21a247debcf5036de95804055150e59 is v0.8.1 release candidate 0 and should fix the problem and solve some compatibility issues with older version of Python that surfaced with previous fixes. I plan to release version 0.8.1 on the master branch and PyPI next week. 

I was not able to consistently replicate this bug on my testing machines, but I'm highly confident that it is related to `socket.recv(nbytes, socket.MSG_WAITALL)` returning less than `nbytes`.

**Comment by miccoli** [comment]
Fixed in https://github.com/miccoli/pyownet/tree/v0.8.1
