### ISSUE TITLE
pyownet display incomplete sensor list

### ISSUE THREAD

**Issue by omcdr** [miccoli/pyownet#3]
In my owfs system I have 7 sensors:
<pre>
ls /mnt/1wire/
05.4AEC29CDBAAB  10.120169020800  10.1E0B69020800  10.31DE68020800  10.67C6697351FF  10.B50F69020800  10.D80669020800 
</pre>

but pyownet under Python 3.4 see only 2

<pre>
Python 3.4.2 (default, Dec  3 2014, 09:03:21)
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyownet import protocol
>>> owproxy = protocol.proxy(host="192.168.7.21", port=4304)
>>> owproxy.ping()
>>> owproxy.dir()
['/10.67C6697351FF/', '/05.4AEC29CDBAAB/']
</pre>

How to debug this issue ?

**Comment by omcdr** [comment]
Tested on
<pre>
owserver -V
owserver version:
        2.8p15
libow version:
        2.8p15
</pre>

**Comment by miccoli** [comment]
`pyownet` queries `owserver` while it is `owfs` that is responsible of the fuse filesystem at `/mnt/1wire`: there is no guarantee that `owserver` and `owfs` share the same configuration, so different sensors may show up, depending on configuration. 

To debug this issue please run from the shell

    $ owdir -s 192.168.7.21:4304

which should give the same result of 

    >>> proxy = protocol.proxy(host="192.168.7.21", port=4304)
    >>> proxy.owdir()

Please attach also your `owserver`  and `owfs` configuration (usually at `/etc/owfs.conf`)

**Comment by omcdr** [comment]
Hmm, after two days it is working correctly, I have the same result in owfs and in owserwer
I don't see incorrect serials 05.4AEC29CDBAAB and 10.67C6697351FF in owfs.
Can you check my owfs.conf ?


<pre>
# owdir -s 192.168.7.21:4304
/10.D80669020800
/10.B80E69020800
/10.120169020800
/10.1E0B69020800
/10.31DE68020800
/10.B50F69020800
/bus.0
/uncached
/settings
/system
/statistics
/structure
/simultaneous
/alarm
</pre>

<pre>
>>> owproxy = protocol.proxy(host="192.168.7.21", port=4304)
>>> owproxy.ping()
>>> owproxy.dir()
['/10.D80669020800/', '/10.B80E69020800/', '/10.120169020800/', '/10.1E0B69020800/', '/10.31DE68020800/', '/10.B50F69020800/']
</pre>

<pre>
#cat /etc/rc.local
/usr/bin/owfs -d /dev/1wire -m /mnt/1wire
</pre>

<pre>
# cat /etc/owfs.conf
# Sample configuration file for the OWFS suite for Debian GNU/Linux.
#
#
# This is the main OWFS configuration file. You should read the
# owfs.conf(5) manual page in order to understand the options listed
# here.

######################## SOURCES ########################
#
# With this setup, any client (but owserver) uses owserver on the
# local machine...
#! server: server = 127.0.0.1:4304
#
# ...and owserver uses the real hardware, by default fake devices
# This part must be changed on real installation
#server: FAKE = DS18S20,DS2405
#
# USB device: DS9490
#server: usb = all
#
# Serial port: DS9097
device = /dev/1wire
#
# owserver tcp address
#server: server = 192.168.10.1:3131
#
# random simulated device
#server: FAKE = DS18S20,DS2405
#
######################### OWFS ##########################
#
#mountpoint = /mnt/1wire
allow_other
#
####################### OWHTTPD #########################
http: port = 2121
####################### OWFTPD ##########################
ftp: port = 2120
####################### OWSERVER ########################
server: port = 0.0.0.0:4304
</pre>

**Comment by miccoli** [comment]
You cannot have both `owserver` and `owfs` access the `/dev/1wire` bus at the same time: the correct configuration is to have `owfs` query the `owserver`

E.g. in `/etc/owfs.conf` you may have

    server: device = /dev/1wire
    server: port = 0.0.0.0:4304
    owfs: server = localhost:4304
    owfs: mountpoint = /run/owfs/1wire
    owfs: allow_other

and you can run

    $ mkdir -p /run/owfs/1wire
    $ /opt/bin/owserver -c /etc/owfs.conf
    $ /opt/bin/owfs -c /etc/owfs.conf

or (more directly without the .conf file and only command line options)

    $ mkdir -p /run/owfs/1wire
    $ /opt/bin/owserver -d /dev/1wire -p 0.0.0.0:4304
    $ /opt/bin/owfs -s localhost:4304 -m /run/owfs/1wire --allow_other

(Please note that I like to mount the fuse filesystem under `/run/owfs/1wire`; mount point `/mnt` has a totally different purpose.)

**Comment by miccoli** [comment]
I'm closing this issue since it is not related to [pyownet](https://github.com/miccoli/pyownet) but to the [OWFS configuration](http://owfs.org/index.php?page=configuration-file). A great place for asking for support is the mailing list at [owfs-developers](https://lists.sourceforge.net/lists/listinfo/owfs-developers).

**Comment by miccoli** [comment]
As a side note `owproxy.ping()` is just for checking if the owserver is alive: no need to issue this command before an `owproxy.read()`.
