### ISSUE TITLE
Relicense as LGPL

### ISSUE THREAD

**Issue by kalvdans** [miccoli/pyownet#9]
We want to use ownet from a proprietary Python program, and thus can not accept the GPL license. Would you consider relicensing pyownet? Feel free to close the bug right away if you want to keep it GPL.

**Comment by miccoli** [comment]
Thank you for your interest in pyownet.

I'm not contrary in principle to a more permissive license, but I need some time to properly understand the licensing and relicensing issues. I will consider your request for the next release, due in Jan-2017.

**Comment by mgiaco** [comment]
Any news here?
cheers mathias

**Comment by miccoli** [comment]
@mgiaco development on version 0.11.0 has stalled... so I just forgot this issue.

If there is still interest for a more permissive license I can issue a ver. ~0.10.1~ 0.10.0.post1 with a new license (e.g. LGPL v3).

If possible I would also know the opinion of the contributors @stromnet and @agentmnm if they are favourable on having a less restrictive licensing.

**Comment by stromnet** [comment]
My contribution to this was very small, so I don't feel that I have much to say.. No objections :)

**Comment by agentmnm** [comment]
yes, I have absolutely not objections. Go ahead.

**Comment by miccoli** [comment]
new LGPLv3+ license released in 9afd404c in master branch
